server:
  port: 8888
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 防止Spring Boot 2.7.X 与 SpringFox路径匹配不一致报错
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.137.128:3306/scaffold?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 970049938
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 15
      # 最大连接数
      max-active: 30
      # 超时时间(以秒数为单位)
      remove-abandoned-timeout: 180
      # 获取连接超时时间
      max-wait: 3000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
      test-while-idle: true
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      # 是否在归还到池中前进行检验
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    #数据库索引
    database: 15
    host: 192.168.137.128
    port: 19700
    password: 970049938
    #连接超时时间
    timeout: 5000

logging:
  level:
    com.weiho.scaffold: DEBUG #开启Mybatis Log Plugin sql日志

#Mybatis  - - -  resultMap 不用全写映射，当数据库中的某些字段不匹配时，只用写某些字段
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml # 扫描所有XML的位置
  global-config:
    db-config:
      id-type: auto # 采用数据库的自增模式
    banner: false # 关闭控制台banner输出
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler # 处理枚举类
#  type-aliases-package: com.r6.**.entity # 别名注解扫描路径

# PageHelper 分页插件
pagehelper:
  helperDialect: mysql
  #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页，
  #pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，
  #自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  supportMethodsArguments: true
  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属
  #性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值，
  #默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero。
  params: count=countSql

scaffold:
  version: 1.0-SNAPSHOT
  jwt:
    # token的请求头的key
    header: Authorization
  code:
    # 存储在Redis中验证码的 Key
    code-key: Scaffold-VerifyCode-key-
    # 验证码过期时间 2 Min
    expiration: 2
  swagger:
    # 是否开启Swagger
    enabled: true
    # Swagger标题
    title: Scaffold - 后台API接口文档
    # 描述
    description: 用于实时查看、测试API、提供前端使用
    # 版本
    version: SNAPSHOT
  thread-pool:
    # 核心线程数
    corePoolSize: 20
    # 最大线程数
    maxPoolSize: 40
    # 队列大小
    queueCapacity: 999
    # 活跃时间
    keepAliveSeconds: 300
    # 线程名称前缀
    namePrefix: Scaffold-async-thread-
  limit:
    # 是否开启接口限流
    enabled: true
  monitor:
    # 是否开启 WebSocket 系统状态监控
    enabled: false
